services:
  bot:
    image: ghcr.io/fldebug10/cactus-bot:master
    container_name: cactus-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      -  ./data:/app/data
