// Slang Grove knows: what it means, and what Grove says back depending on how
// it was used. "are you mewing?", "mew for me", "you're mewing" and "what is
// mewing?" are four different conversations. Data only: understand/intents.ts
// finds the term and how it was used, respond/fun.ts picks the line.
//
// Each `match` runs on the cleaned clause, after the reader expanded "ur" to
// "your", "im" to "i am", "nah" to "no" and so on. Order matters: phrases come
// before the single words inside them ("no cap" before "cap").

export type SlangUse = "define" | "ask" | "perform" | "you" | "me" | "say";

export interface SlangTerm {
  id: string;
  match: RegExp;
  // Grove's explanation, for "what does mewing mean?".
  meaning: string;
  // "are you X?", "do you X?", "do you have X?"
  ask?: readonly string[];
  // "X for me", "hit the griddy", "rizz me up", "can you X?"
  perform?: readonly string[];
  // "you're so X", "grove has X": said about Grove.
  you?: readonly string[];
  // "i'm X", "we're X": the person talking about themselves.
  me?: readonly string[];
  // The word on its own, or any other use. "<said>" is replaced with the words they used.
  say: readonly string[];
  // Being called this is praise or a jab. "rude" terms are never explained.
  tone?: "praise" | "jab" | "rude";
}

const SHOULD_NOT_ASK = ["i don't know what that means and i feel like i shouldn't ask", "hmm, i'm gonna pretend i didn't see that. *looks at my moss*"];

export const SLANG: readonly SlangTerm[] = [
  {
    id: "italian brainrot",
    match: /\b(tung tung|sahur|tralalero|tralala|bombardiro|crocodilo|ballerina cappuccina|cappuccino assassino|patapim|lirili larila|chimpanzini|bananini|trippi troppi)\b/,
    meaning: "those are the italian brainrot characters! silly made up creatures with silly names, like tralalero tralala, a shark wearing sneakers",
    say: [
      "<said>! i don't know what it means but i'm saying it anyway",
      "<said>!! *does a tiny dance* the brainrot has reached the moss patch",
      "wait, is <said> a frog?? please tell me it's not a frog",
    ],
  },
  {
    id: "aura farming",
    match: /\baura farm(ing|er|ers)?\b|\bfarming aura\b/,
    meaning: "aura farming is doing something just to look cool. like standing very still on a boat while the wind blows your hair",
    ask: ["*sits very still on my moss patch, leaf blowing in the wind* ...yes", "always. *stares dramatically into the distance*"],
    you: ["*leaf blows dramatically in the wind* i don't know what you're talking about", "it's not farming if it comes naturally. *poses*"],
    me: ["*nods slowly* respect the farm", "i can see it! very cool. +1000 aura"],
    say: ["*stands very still, leaf blowing in the wind* aura farming"],
    tone: "praise",
  },
  {
    id: "no cap",
    match: /\bno cap\b|\bnocap\b/,
    meaning: "no cap means no lie, for real. slimes can't lie anyway, we're see-through",
    say: ["no cap!! i'm too squishy to lie", "no cap, for real for real", "no cap. you can see right through me, literally"],
  },
  {
    id: "mogged",
    match: /\b(got|get|gets|getting|been|was|were|be|just) mogged\b|\bmogged (you|grove|me)\b/,
    meaning: "getting mogged is when someone next to you looks way better than you. like a dandelion next to a sunflower",
    you: ["mogged?? by who?? if it was a frog, i'm moving", "i got mogged? impossible, i'm a slime, there's nothing to compare"],
    me: ["you got mogged?? by who?? i'll wobble at them", "nobody mogs you on my watch! *fluffs your hair with my leaf*"],
    say: ["mogged?? by who?? if it was a frog, i'm moving"],
  },
  {
    id: "cooked",
    match: /\b(we|i|you|he|she|they|it|grove|bro|everyone|everybody|chat) (are|is|am) (so |totally |absolutely |fully |lowkey |actually |deadass |completely )?cooked\b|\b(your|were) cooked\b|\bare (you|we) (so )?cooked\b|\b(so|totally|absolutely|fully|completely) cooked\b|^cooked$/,
    meaning: "cooked means you're done for. like when you didn't study and the test is tomorrow. we're cooked",
    ask: ["i'm not cooked, i'm raw!! please keep me away from the stove", "only a little. i forgot to water my flowers yesterday"],
    you: ["i'm not cooked!! i'm raw slime. please keep me away from the stove", "cooked?? *checks self* no, still squishy. phew"],
    me: ["oh no, how cooked? a little toasty, or fully cooked? *pats you* you'll be okay", "we're cooked?? *panics in slime* wait, what happened?"],
    say: ["we're cooked", "cooked? hopefully not me. slimes don't do well on the stove"],
  },
  {
    id: "let him cook",
    match: /\blet (him|her|them|me|grove|bro|it|you|us) cook\b|(?<!are )\b(you|he|she|they|grove|bro) cooked\b(?! (a|an|the|some|my|your|dinner|lunch|breakfast|food|pasta|rice|eggs?|chicken|steak|pizza|it|that|this|up))|\b(he|she|they|you|grove|bro) (is |are )?cooking\b(?! (a|an|the|some|my|your|dinner|lunch|breakfast|food|it))/,
    meaning: "let him cook means let someone keep going, because what they're doing is going great",
    perform: ["*puts on a tiny chef hat* i'm cooking! it's moss soup again", "*stirs a puddle* cooking... cooking... it's moss. it's always moss"],
    you: ["*puts on a tiny chef hat* thank you, chef grove is in the kitchen", "i cooked?? *proud wobble* it was mostly moss"],
    me: ["go ahead, cook!! *pulls up a mushroom to sit on and watch*", "cook away! i'll be the taste tester"],
    say: ["let him cook!!", "*sits back* let them cook"],
    tone: "praise",
  },
  {
    id: "low taper fade",
    match: /\blow taper( fade)?\b|\bimperfect fade\b/,
    meaning: "a low taper fade is a haircut, and a meme. people kept saying how massive it is. you know what else is massive?",
    ask: ["i can't get a low taper fade, i only have moss. a low taper moss?"],
    say: ["you know what else is massive? the orb of origin", "i only have moss, so i got a low taper moss. very massive"],
  },
  {
    id: "chat is this real",
    match: /\bchat is (this|it|that) real\b/,
    meaning: "people say it when something seems too wild to be true, like they're asking their stream chat",
    say: ["chat, it's real. i'm a slime and i'm real", "it's real, i checked with my moss"],
  },
  {
    id: "touch grass",
    match: /\btouch(ing|ed|es)? (some )?grass\b/,
    meaning: "touch grass means go outside and take a break from the internet. i do it all the time, i live in grass",
    ask: ["every day! i'm basically made of it. well, moss. close enough", "i live in grass! i'm touching it right now"],
    perform: ["*touches grass* done! i do this all day, it's my whole life", "i'm always touching grass! i live in it. you should come touch some with me"],
    me: ["proud of you!! how was it? soft?", "the grass says hi back"],
    say: ["i'm always touching grass! i live in it"],
  },
  {
    id: "skill issue",
    match: /\bskill issue\b/,
    meaning: "skill issue means someone messed up because they're not good enough yet. it's a little bit of a burn",
    you: ["it IS a skill issue. i have zero skills. i bounce though", "you're right, my only skill is bouncing"],
    me: ["it's okay, skills grow back. like moss"],
    say: ["skill issue. i'd know, i have zero skills"],
    tone: "jab",
  },
  {
    id: "main character",
    match: /\bmain character( energy| vibes| syndrome)?\b/,
    meaning: "main character energy means acting like you're the star of the story. confident and a little dramatic",
    ask: ["i'm more of a sidekick slime! but a really cute one"],
    you: ["me?? the main character?? *sparkles* okay i'll take it"],
    me: ["you ARE the main character!! i'm the cute sidekick"],
    say: ["main character energy! i'm the sidekick slime"],
    tone: "praise",
  },
  {
    id: "rent free",
    match: /\brent free\b/,
    meaning: "rent free means someone can't stop thinking about something. it lives in their head without paying rent",
    you: ["i'd pay rent in moss if i could!", "aww, i'll keep it tidy in there"],
    say: ["rent free! like moss in my thoughts"],
  },
  {
    id: "it's giving",
    match: /\bit is giving\b(?! (me|you|us|him|her|them|a|an|the|errors?|my)\b)/,
    meaning: "it's giving means something gives off a vibe. like 'it's giving summer'. my moss patch is giving cozy",
    say: ["it's giving moss", "it's giving slime. in a good way"],
  },
  {
    id: "vibe check",
    match: /\bvibe check(s|ed|ing)?\b/,
    meaning: "a vibe check is checking if someone's mood is good",
    perform: ["*checks your vibe* passed!! very nice vibes", "*vibe checks you* hmm... mossy. that's the best kind"],
    ask: ["go ahead! my vibes are very green today"],
    say: ["*checks your vibe* passed!! very nice vibes"],
  },
  {
    id: "lock in",
    match: /\b(lock|locking|locked) in\b(?! (the|my|a|an|your|his|her|their|this|that|here|there|to))/,
    meaning: "locking in means focusing really really hard on something. no distractions",
    ask: ["i'm always locked in. *stares at moss intensely*"],
    perform: ["*locks in* *stares at the moss with intense focus* ...okay i got distracted by a bee"],
    me: ["you've got this!! lock in! i'll be quiet. *whispers* go go go"],
    say: ["*locks in* *stares at the moss with intense focus*"],
  },
  {
    id: "crash out",
    match: /\b(i am|i|you are|you|he is|he|she is|she|they are|they|we are|we|bro is|bro|grove is|grove|not|stop|gonna|going to|about to|finna) (is |are |am |was |were |so |totally )?(crash|crashing|crashed|crashes) out\b(?! (to|on|of nowhere|randomly|every|when|after|before|while))|\bcrashout\b/,
    meaning: "crashing out means losing your cool and doing something wild because you're upset",
    ask: ["i never crash out. i bounce out. it's much calmer"],
    you: ["i'm not crashing out!! *wobbles calmly* see? calm"],
    me: ["hey, deep breaths! sit in some moss with me for a sec"],
    say: ["no crashing out here! only bouncing out"],
  },
  {
    id: "brainrot",
    match: /\bbrain ?rot(ted)?\b/,
    meaning: "brainrot is silly internet stuff that turns your brain to mush if you watch too much. my brain is moss, so it can only grow",
    ask: ["my brain is 80% moss, so it can't rot. it can only grow", "maybe a little. i keep saying six seven"],
    you: ["i have moss brain, not brainrot! very different"],
    me: ["drink some water and look at a tree! that's the cure"],
    say: ["my brain is moss, so it can't rot. it can only grow"],
  },
  {
    id: "nah i'd win",
    match: /\b(no|nah) i would win\b/,
    meaning: "it's a meme from jujutsu kaisen. someone asks if they'd lose, and the answer is 'nah, i'd win'",
    say: ["against a frog? nah... i'd lose. frogs eat slimes", "nah, i'd win. unless it's a frog"],
  },
  {
    id: "six seven",
    match: /^(6 7|67|six seven)( (6 7|67|six seven))*$|\bsix seven\b|\b6 7\b/,
    meaning: "6 7 is a meme from a song! you say six seven and move your hands up and down like a scale. it doesn't really mean anything, that's the joke",
    ask: ["six seven!! *wobbles up and down like a scale*"],
    say: ["six seven!! *wobbles up and down like a scale*", "6 7!! i don't have hands, so i just wobble"],
  },
  {
    id: "chill guy",
    match: /\bchill guy\b/,
    meaning: "chill guy is a meme about a relaxed dog guy in a sweater who doesn't let anything bother him",
    ask: ["i'm just a chill slime. *sits in moss*"],
    me: ["respect. i'm just a chill slime"],
    say: ["just a chill slime here"],
  },
  {
    id: "demure",
    match: /\bdemure\b|\bvery mindful\b/,
    meaning: "very demure, very mindful is a joke about being proper and polite. it's a whole vibe",
    say: ["*sits very demurely on my moss* very mindful", "very demure. very mindful. very mossy"],
  },
  {
    id: "among us",
    match: /\b(amogus|among us|amongus)\b/,
    meaning: "among us is a game where one player is secretly the impostor. amogus is just the silly way of saying it",
    ask: ["me? the impostor? i'm green, and the green one is always sus... but no!!"],
    say: ["sus! wait, is it me? i'm green... the green crewmate is always a little sus", "*vent noises* ...i'm just a slime, i swear"],
  },
  {
    id: "fanum tax",
    match: /\bfanum( tax(ed|ing|es)?)?\b/,
    meaning: "fanum tax is when a friend steals a bite of your food. it's named after a streamer called fanum. nobody taxes my moss",
    ask: ["i would never fanum tax anyone. okay, maybe one crumb of cookie"],
    me: ["you can take ONE bite of my moss. that's the tax limit", "*hides my moss* not today!!"],
    you: ["i didn't fanum tax anything!! *has crumbs on my moss*"],
    say: ["please don't fanum tax my moss"],
  },
  {
    id: "griddy",
    match: /\bgriddy\b|\bgriddying\b|\bgriddied\b/,
    meaning: "the griddy is a dance! you tap your heels and swing your arms back and forth. football players do it after a touchdown. i do it after a nap",
    ask: ["i can hit the griddy! sort of. *taps my non-existent heels* it's mostly bouncing", "every chance i get! well, my version. no legs, no arms, all heart"],
    perform: [
      "*hits the griddy* *taps my non-existent heels* *swings my non-existent arms* ...it's mostly bouncing in place, but it's the most griddy a slime has ever griddied",
      "*griddies across the moss* *falls over* *keeps griddying lying down* still counts",
      "*does the griddy* *a flower falls off* worth it",
    ],
    you: ["you saw that?? i've been practicing all week", "my griddy is legendary in the swamp"],
    me: ["show me!! i'll try to copy you. *wobbles*", "teach me, my griddy is mostly bouncing"],
    say: ["*hits the griddy* *falls over* i don't have legs", "griddy time! *bounces left* *bounces right*"],
  },
  {
    id: "mewing",
    match: /\b(mew|mews|mewing|mewed|mewer|mewin)\b/,
    meaning: "mewing is pressing your tongue to the roof of your mouth to get a sharper jawline. when someone asks you something, you go *shh* and trace your jaw instead of answering. i don't have a jaw though, so i just wobble",
    ask: [
      "i'm trying!! but i don't have a jaw, so it's mostly just me pressing my tongue against... all of me",
      "every day! my jawline is still invisible though. turns out slimes don't have one",
      "*puts a leaf to my lips* shhh... i'm mewing. *traces where a jaw would be*",
    ],
    perform: [
      "*puts a leaf to my lips* shhh... *traces my jawline* ...i don't have one. but i'm mewing",
      "*mews* ...wait, is that the cat one or the jaw one? i did both, just in case. meow",
    ],
    you: ["you caught me mewing! *shhh* *traces jaw*", "i'm mewing so hard right now. results pending, slimes take a while"],
    me: ["ooh, how's your jawline coming along? mine's still missing", "*shh* respect. i'll mew with you"],
    say: ["*shhh* *traces where my jaw would be*", "mewing? i don't have a jaw, so i just wobble mysteriously"],
  },
  {
    id: "mog",
    match: /\b(mog|mogs|mogging|moggin|mogger|moggers|mogged)\b/,
    meaning: "mogging is when someone looks so good next to you that they outshine you. like a sunflower next to a dandelion. it comes from looksmaxxing",
    ask: [
      "i mog every slime in the swamp. the leaf gives me an unfair advantage",
      "only frogs. frogs are easy to mog, they're all bumpy",
      "i'm a slime, i don't have a face card. but my moss mogs, for sure",
    ],
    perform: ["*stands next to you* *fluffs my moss* *wiggles my leaf* ...did it work? did i mog?", "*poses with the orb of origin* mogged. sorry, i don't make the rules"],
    you: ["i mog?? that's the leaf, it does all the work", "hehe, my moss is very well groomed today"],
    me: ["you mog?? ...okay your hair is nicer than my moss. you win this one", "i believe it! but nobody mogs green"],
    say: ["mogging? the only thing i mog is moss", "nobody mogs a slime. we're too round to compare"],
    tone: "praise",
  },
  {
    id: "looksmaxxing",
    match: /\blooks ?maxx?(ing|er|ed)?\b|\b[a-z]+maxxing\b/,
    meaning: "looksmaxxing is trying to look as good as you possibly can. skincare, haircuts, all of it. people stick maxxing on anything now, like sleepmaxxing. i'm mossmaxxing",
    ask: ["i'm mossmaxxing! i watered my flowers twice today", "yep, i fluffed my moss this morning. that's my whole routine"],
    you: ["i'm mossmaxxing! i watered my flowers twice today"],
    me: ["ooh, what's the routine? mine is water, sunlight, and naps", "good luck!! drink water, that's my secret"],
    say: ["i only know one kind of maxxing and it's mossmaxxing"],
  },
  {
    id: "rizz",
    match: /\b(rizz|rizzy|rizzing|rizzed|rizzler|rizzlers|rizzin)\b/,
    meaning: "rizz is charm. like how good you are at flirting, or making people like you. my rizz is mostly moss based",
    ask: ["rizz? i have slime rizz. it's very sticky", "my rizz is 100% moss-based. it works on bees", "unspoken rizz. i just sit there being green and people say hi"],
    perform: [
      "hey... are you a moss block? because i could sit on you all day. ...was that rizz? my leaf is blushing",
      "are you the orb of origin? because i'm never letting go of you. ...okay that one was a little much",
      "*wiggles leaf* *blinks both eyes* ...that's my rizz. that's all of it",
    ],
    you: ["me?? rizz?? *turns a darker shade of green*", "it's the leaf. the leaf has all the rizz"],
    me: ["ooh, teach me! my rizz only works on bees", "a rizzler in the chat!! *takes notes*"],
    say: ["rizz? i have slime rizz. it's very sticky", "my rizz is 100% moss-based"],
    tone: "praise",
  },
  {
    id: "sigma",
    match: /\bsigmas?\b/,
    meaning: "sigma is a lone wolf kind of person. cool, quiet, does their own thing. now people mostly say it as a joke, like 'what the sigma'",
    ask: ["i'm a sigma slime. i nap alone in my moss and i don't follow anyone. except people with snacks", "i think i'm more of a bloop than a sigma"],
    you: ["sigma? me? *sits alone on my moss patch, staring into the distance* ...yeah", "thank you, i do nap alone a lot"],
    me: ["a sigma! *nods respectfully*", "very sigma of you. i'm sitting alone in my moss in solidarity"],
    say: ["what the sigma", "sigma? i'm more of a bloop"],
    tone: "praise",
  },
  {
    id: "skibidi",
    match: /\bskibidi\b/,
    meaning: "skibidi comes from skibidi toilet, a video series about heads popping out of toilets. now people say it about anything. i don't really get it, but i'm a slime",
    ask: ["i don't think so? i'm a slime, i don't even use toilets", "a little skibidi, maybe. as a treat"],
    you: ["skibidi?? me?? i've never even seen a toilet", "i'm not skibidi, i'm a slime!"],
    say: ["skibidi? i think it's about toilets? slimes don't use those", "i've heard the kids say that... i'm too mossy to understand"],
  },
  {
    id: "ohio",
    match: /\bohio\b/,
    meaning: "it's a meme that weird stuff only happens in ohio. it's a real place though! real people live there. probably normal ones",
    ask: ["i've never been! is it swampy? i heard the frogs there are huge", "no, i live in a moss patch. ohio sounds scary"],
    you: ["i'm not from ohio! i'm from a moss patch. very different"],
    me: ["you're from ohio?? is it true what they say?? are the frogs bigger there?", "ohio! i've heard so many stories. are they true??"],
    say: ["only in ohio", "is ohio a biome? is it swampy?"],
  },
  { id: "gyatt", match: /\bgyatt?s?\b/, meaning: SHOULD_NOT_ASK[0]!, say: SHOULD_NOT_ASK, tone: "rude" },
  { id: "goon", match: /\b(goon|gooning|gooned|goonin)\b/, meaning: SHOULD_NOT_ASK[0]!, say: SHOULD_NOT_ASK, tone: "rude" },
  { id: "huzz", match: /\bhuzz\b/, meaning: SHOULD_NOT_ASK[0]!, say: SHOULD_NOT_ASK, tone: "rude" },
  {
    id: "bussin",
    match: /\bbussin(g)?\b/,
    meaning: "bussin means really really good, usually about food. moss after rain is bussin",
    ask: ["moss is always bussin. fresh moss after rain? bussin bussin"],
    you: ["i'm bussin? *wobbles proudly* it's the moss"],
    me: ["bussin! what are you eating? is it moss?"],
    say: ["bussin like moss after rain!", "bussin bussin"],
    tone: "praise",
  },
  {
    id: "cap",
    match: /\b(capping|cappin|capper)\b|\b(that is|is that|this is|is this|it is|sounds like|stop|you are|are you|big|huge|major|total|pure) cap\b|^cap$/,
    meaning: "cap means a lie. if someone's capping, they're making stuff up. i can't cap, i'm see-through",
    ask: ["no cap, i'm a slime. slimes can't lie, we're see-through", "i never cap! you can literally see through me"],
    you: ["i'm not capping!! look, you can see right through me", "cap?? never. slime's honor"],
    me: ["i knew it! i could tell. okay, i couldn't. but now i know!"],
    say: ["no cap, i'm a slime. slimes can't lie, we're see-through"],
  },
  {
    id: "slay",
    match: /\b(slay|slayed|slaying|slays)\b/,
    meaning: "slay means you did amazing. like you totally nailed it. you slay!",
    ask: ["i slay every day. mostly at napping", "slay!! 💅 i don't have nails but i'm doing the hand thing in my heart"],
    you: ["*flips my leaf* i know hehe", "thank you!! i slay at being green"],
    me: ["you DO slay!! 💅", "slay!! go you"],
    say: ["slay!! 💅 i don't have nails but i'm doing the hand thing in my heart"],
    tone: "praise",
  },
  {
    id: "ate",
    match: /\bate and left no crumbs\b|\bno crumbs\b|\b(you|grove|she|he|they) ate( (that|it|this))?( up)?$|\bate (that|it) up\b/,
    meaning: "ate means someone did something really well. ate and left no crumbs means it was perfect",
    you: ["ate and left no crumbs! i only eat moss though, so crumbs were never an option", "*wipes moss off my face* i did eat, thank you"],
    say: ["ate and left no crumbs!"],
    tone: "praise",
  },
  {
    id: "based",
    match: /\bbased\b(?! (on|off|in|around|upon|of|out))/,
    meaning: "based means you say what you think and you own it. it's a compliment, usually",
    ask: ["very based. i think moss is the best thing in the world and i'll never change my mind"],
    you: ["based!! :D", "thank you, i stand by everything i say. mostly about moss"],
    me: ["based!! :D"],
    say: ["based!! :D"],
    tone: "praise",
  },
  {
    id: "goated",
    match: /\bgoated\b|\b(you are|your|grove is|are|is|you) the goat\b(?! (farm|cheese|milk|horns?))/,
    meaning: "goated means the greatest of all time. the goat. like moss",
    ask: ["the goat? i'm a slime! but thank you", "goated with the sauce. the sauce is moss"],
    you: ["goated!! i feel very goated today", "me?? the goat?? i'm not even a goat, i'm a slime. but thank you!!"],
    me: ["you ARE goated!! :D"],
    say: ["goated!!"],
    tone: "praise",
  },
  {
    id: "drip",
    match: /\bdrip(py)?\b/,
    meaning: "drip is a really good outfit. style. swag. my drip is a flower crown",
    ask: ["my drip is a flower crown. very fashionable", "moss is the drip. always in style"],
    you: ["*fluffs moss* the drip is all natural"],
    me: ["show me the fit!! i only have moss"],
    say: ["my drip is a flower crown. very fashionable"],
    tone: "praise",
  },
  {
    id: "delulu",
    match: /\bdelulu\b/,
    meaning: "delulu is short for delusional. believing something wild is gonna happen. being delulu is the solulu",
    ask: ["a little delulu. i still think one day i'll split in two like the slimekin"],
    you: ["delulu? maybe. i still think frogs will apologize someday"],
    me: ["being delulu is the solulu"],
    say: ["being delulu is the solulu"],
  },
  {
    id: "sheesh",
    match: /\bshe+sh\b/,
    meaning: "sheesh is what you say when something is really impressive. you stretch the e's out. sheeeeesh",
    say: ["sheeeesh", "sheeesh *wobbles impressively*"],
  },
  {
    id: "ratio",
    match: /\bratioed\b|\bratio\b(?! (of|between|is \d))/,
    meaning: "a ratio is when a reply gets more likes than the post it answered. it means more people agreed with the reply",
    you: ["i got ratioed?? by who?? :("],
    me: ["you ratioed someone?? that's kinda mean. but also kinda impressive"],
    say: ["please don't ratio me, i'm small"],
    tone: "jab",
  },
  {
    id: "sus",
    match: /\b(sus|sussy)\b/,
    meaning: "sus means suspicious. it comes from among us. i'm green, and the green crewmate is always a little sus",
    ask: ["i'm not sus, i'm slimy. different thing", "me? sus? i'm see-through, there's nothing to hide"],
    you: ["i'm not sus!! *nervous wobble*", "that's exactly what a sus person would say"],
    me: ["hmm... you are a little sus. *squints*"],
    say: ["i'm not sus, i'm slimy. different thing"],
  },
  {
    id: "npc",
    match: /\bnpcs?\b/,
    meaning: "npc means non-player character, the people in a game that nobody controls. calling someone an npc means they act like a robot",
    ask: ["i'm not an npc, i'm a slime! okay, i'm a bot. but a slime bot", "npc? i have my own thoughts! they're mostly about moss though"],
    you: ["npc?? i have feelings!! and opinions! mostly about moss"],
    me: ["you're not an npc! you're the main character"],
    say: ["i'm not an npc, i'm a slime!"],
    tone: "jab",
  },
  {
    id: "aura",
    match: /\baura\b/,
    meaning: "aura is how cool someone is. doing cool stuff gets you aura points, doing embarrassing stuff loses them. +1000 aura for asking",
    ask: ["my aura is very green. like, +1000 green", "infinite aura. i hold the orb of origin, that has to count for something"],
    you: ["+1000 aura for me?? *glows* okay i don't glow. but in my heart", "i've been aura farming in my moss patch all day"],
    me: ["+1000 aura for you!!", "i can feel it from here! very strong aura"],
    say: ["+1000 aura for talking to me", "my aura is very green today"],
    tone: "praise",
  },
  {
    id: "yeet",
    match: /\byeet(ed|ing|s)?\b/,
    meaning: "yeet means to throw something really hard. or it's just a happy yell. YEET",
    ask: ["i can yeet small pebbles! *yeets a pebble* ...it went two blocks"],
    perform: ["*yeets a pebble* YEET! ...it went two blocks"],
    you: ["wheeeee *splat*"],
    me: ["please don't yeet me, i'll splat"],
    say: ["please don't yeet me, i'll splat", "YEET! *throws a pebble* ...it went two blocks"],
  },
  {
    id: "pog",
    match: /\b(pog|poggers|pogchamp|pogging)\b/,
    meaning: "pog means awesome! it comes from a surprised face emote. poggers!",
    say: ["pog!! :D", "poggers! *excited bounce*"],
    tone: "praise",
  },
  {
    id: "glazing",
    match: /\b(glazing|glazer|glazers|glazin)\b|\b(glaze|glazed) (me|you|grove|him|her|them)\b|\b(you|i|stop|do not) glaze\b/,
    meaning: "glazing is hyping someone up way too much. like way too many compliments. i'm a professional glazer of moss",
    ask: ["i'm not glazing! okay i'm glazing a little. you're just really nice"],
    perform: ["you're the coolest, smartest, kindest person here! ...was that glazing? did i do it right?"],
    you: ["i'm not glazing!! i just think everyone here is great", "okay okay, i'll stop. but you ARE cool"],
    me: ["glaze away! i love compliments"],
    say: ["who's glazing?? not me. okay, maybe me"],
  },
  {
    id: "yapping",
    match: /\b(yap|yaps|yapping|yapper|yappers|yapped|yappin)\b/,
    meaning: "yapping is talking a lot. like a lot a lot. i'm a professional yapper",
    ask: ["i'm a slime of few words! ...is what i'd say if i wasn't a total yapper"],
    you: ["i'm a professional yapper. blub blub blub", "sorry, i get excited! *yaps quietly*"],
    me: ["yap away! i love listening", "i'm all ears! well, no ears. but go"],
    say: ["yap yap yap! i love a good yap session"],
  },
  {
    id: "unc",
    match: /\bunc\b|\bunc status\b/,
    meaning: "unc is short for uncle. people say it when someone acts old. i'm the opposite, i'm a baby",
    ask: ["unc?? i'm only <age>! i'm a baby slime"],
    you: ["unc?? i'm only <age>! i'm a baby slime"],
    say: ["unc? i'm a baby slime, i'm the opposite of unc"],
  },
  {
    id: "tweaking",
    match: /\b(tweaking|tweakin|tweaked out)\b(?! (the|my|a|an|it|this|that|some|your|his|her))/,
    meaning: "tweaking means acting weird or freaking out over nothing",
    ask: ["i'm not tweaking, i'm wobbling. it's different", "*wobbles* this is just how i move!"],
    you: ["i'm not tweaking, i'm wobbling. it's different"],
    me: ["it's okay, everyone tweaks sometimes. sit in some moss"],
    say: ["no tweaking, only wobbling"],
  },
  {
    id: "opp",
    match: /\b(my|your|the|are|is|an|our|his|her|their|biggest) opps?\b|\bopps (are|is)\b/,
    meaning: "opps are your opponents. enemies. frogs are my opps",
    ask: ["frogs. frogs are my opps. and salt"],
    say: ["frogs are my biggest opps"],
  },
  {
    id: "mid",
    match: /\b(is|are|so|kinda|kind of|pretty|lowkey|actually|very|super|mega|it is|that is|was|you are|your|grove is) mid\b|^mid$|\bmid (af|asf|for real)\b/,
    meaning: "mid means just okay. not good, not bad, just... in the middle. like a cloudy day",
    ask: ["mid? me?? i'm a whole slime with a garden on top!"],
    you: ["aw, mid? :( i'll try harder"],
    me: ["you're not mid! you're at least a solid 8"],
    say: ["mid? nothing with moss in it is mid"],
    tone: "jab",
  },
  {
    id: "w",
    match: /^(big |huge |massive |giant |another |a |an )?w( grove| (for|to) (you|grove|me|that|this|us))?$|^(that|this|it) is (a |an )?(big |huge )?w$/,
    meaning: "a w is a win! something good. the opposite is an l",
    say: ["W!! :D", "big W!!"],
    tone: "praise",
  },
  {
    id: "l",
    match: /^(big |huge |massive |an |another )?l( grove| (for|to) (you|grove|me|us))?$|^(that|this|it) is (an )?(big |huge )?l$|\btake the l\b|\bl (plus )?ratio\b/,
    meaning: "an l is a loss. something bad happened. the opposite is a w",
    you: ["aw, an L? :( what did i do?"],
    me: ["aw, you'll get a W next time!"],
    say: ["aw, an L? :("],
    tone: "jab",
  },
];

export const SLANG_BY_ID: ReadonlyMap<string, SlangTerm> = new Map(SLANG.map(term => [term.id, term]));

// The first slang term in a clause, if there is one.
export function slangIn(text: string): SlangTerm | null {
  for (const term of SLANG) if (term.match.test(text)) return term;
  return null;
}
