// Regenerates src/brain/content/realWords.ts:  node scripts/speller-audit.ts
//
// Grove fixes typos toward a short list of words that matter (see
// CORRECTION_TARGETS). Some real English words sit one or two letters away
// from those targets ("cash" from "crash", "force" from "forge"), and those
// must never be "fixed". This script runs every English word through the
// speller and writes the ones it would change to realWords.ts, so the speller
// leaves them alone. Run it after editing CORRECTION_TARGETS or KNOWN_WORDS;
// test/speller.test.ts fails until you do.

import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { CONTRACTIONS, CORRECTION_TARGETS, KNOWN_WORDS, SLANG } from "../src/brain/content/words.ts";
import { GROVE_NAMES } from "../src/brain/text/reader.ts";
import { Speller } from "../src/brain/text/speller.ts";

const require = createRequire(import.meta.url);
const english = require("an-array-of-english-words") as string[];

const speller = new Speller(new Set([...KNOWN_WORDS, ...Object.keys(SLANG), ...Object.keys(CONTRACTIONS), ...GROVE_NAMES]), CORRECTION_TARGETS);
const collisions = english.filter(word => /^[a-z]+$/.test(word) && speller.correct(word) !== word).sort();

const lines: string[] = [];
let line = "";
for (const word of collisions) {
  if (line.length + word.length + 1 > 110) {
    lines.push(line.trimEnd());
    line = "";
  }
  line += `${word} `;
}
if (line.length > 0) lines.push(line.trimEnd());

const file = `// Generated by scripts/speller-audit.ts. Do not edit by hand.
// Real English words that sit a typo away from one of Grove's correction
// targets. The speller never changes these.

export const REAL_WORDS: ReadonlySet<string> = new Set(\`
${lines.join("\n")}
\`.trim().split(/\\s+/));
`;

writeFileSync(fileURLToPath(new URL("../src/brain/content/realWords.ts", import.meta.url)), file);
console.log(`wrote ${collisions.length} protected words`);
